### PR TITLE
Synchronized stdout

### PR DESCRIPTION
**Pull request by nchapman**
Enabled synchronized stdout so that apnmachined output shows up when using foreman (https://github.com/ddollar/foreman/wiki/Missing-Output).

### CODE REVIEW

**Comment by jnak** [comment]
Thanks Nick,

Never had any issue with this, but makes sense. Just chiming here, but can you move this edit right after log = STDOUT on line #43 ?

**Comment by nchapman** [comment]
Yep no problem. I didn't know if you wanted it nestled right up to that log line or not. It's funny how it just doesn't feel quite right anywhere in the file :).

**Comment by jnak** [comment]
You're right :) Thx

Are you happy with ApnMachine ?

**Comment by nchapman** [comment]
Yeah so far it's great! Thanks for all the hard work! I've written a few apps with em-synchrony, so I was excited to find this. I'm using ApnMachine with a Rails app that does mobile device management, and everything to do with Apple's MDM implementation works slightly differently, so I might have a few more changes for your consideration. Hopefully they'll be more interesting than this one...

**Comment by jnak** [comment]
I'm glad you like and use it! There is no small change :)

**Pull request merged**
